// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Upgrade:                              1
// Endpoints:                           12
// Async Callback (empty):               1
// Total number of exported functions:  15

#![no_std]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    experience
    (
        init => init
        upgrade => upgrade
        addManager => add_manager_endpoint
        removeManager => remove_manager_endpoint
        getDaoVoteWeight => get_dao_vote_weight_view
        getDaoMembers => get_dao_members_view
        addPoints => add_points_endpoint
        removePoints => remove_points_endpoint
        addTier => add_tier_endpoint
        clearAllTiers => clear_all_tiers_endpoint
        getMemberPoints => get_member_points_view
        getMemberTier => get_member_tier_view
        getAllTiers => get_all_tiers_view
        getManagers => managers
    )
}

multiversx_sc_wasm_adapter::async_callback_empty! {}
