// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Endpoints:                            6
// Async Callback (empty):               1
// Total number of exported functions:   8

#![no_std]
#![allow(internal_features)]
#![feature(lang_items)]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    experience
    (
        init => init
        upgrade => upgrade
        getDaoVoteWeight => get_dao_vote_weight_view
        getDaoMembers => get_dao_members_view
        addXp => add_xp_endpoint
        removeXp => remove_xp_endpoint
        getManagers => managers
    )
}

multiversx_sc_wasm_adapter::async_callback_empty! {}
